export const ActionTypes = {
  GET_DATA_FROM_JSON        : 'GET_DATA_FROM_JSON',
  SET_CATEGORY_LIST         : 'SET_CATEGORY_LIST',
  SET_SELECTED_CATEGORY     : 'SET_SELECTED_CATEGORY',
  DELET_SPECIFIC_MOVIE      : 'DELET_SPECIFIC_MOVIE',
  SET_MOVIE_LIKE          : 'SET_MOVIE_LIKE',
  CANCEL_MOVIE_LIKE       : 'CANCEL_MOVIE_LIKE ',
  SET_MOVIE_DESLIKE       : 'SET_MOVIE_DESLIKE',
  CANCEL_MOVIE_DESLIKE    : 'CANCEL_MOVIE_DESLIKE',
  SET_ITEM_PER_PAGE         : 'SET_ITEM_PER_PAGE',
  SET_CURRENT_PAGE          :  'SET_CURRENT_PAGE',
  SET_MAX_PAGE_NUMBER_LIMIT : 'SET_MAX_PAGE_NUMBER_LIMIT',
  SET_MIN_PAGE_NUMBER_LIMIT : 'SET_MIN_PAGE_NUMBER_LIMIT',
  SET_PAGES                 : 'SET_PAGES '
}